### ISSUE TITLE
@conda-forge-admin, please add user @traversaro

### ISSUE THREAD

**Issue by traversaro** [conda-forge/nevergrad-feedstock#31]
### Additional comment:

@conda-forge-admin, please add user @traversaro

**Comment by aldanor** [comment]
@traversaro Do you want to be added to the maintainer list? I can add you in the next PR if you'd like.

**Comment by traversaro** [comment]
> @traversaro Do you want to be added to the maintainer list? I can add you in the next PR if you'd like.

Thanks! I do not remember why I did this, probably I wanted to update the nevergrad version released in conda-forge, as you did, so the immediate problem is solved. If you like and to reduce the bus factor feel free to add me to the mantainers, thanks!
