### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by ytsaig** [conda-forge/nevergrad-feedstock#32]
Thank you for maintaining this feedstock. It looks like it's gone a bit stale, nevergrad is currently at 0.11: https://github.com/facebookresearch/nevergrad/releases. Would it be possible to update the feedstock to the latest version? Thank you!

**Comment by aldanor** [comment]
0.13 = just published.

(Will probably issue another build for it where ax-platform is removed as a mandatory dep, but anyways the latest version is there.)
